{
 "title": "Infrastructure Comprehensive Monitoring",
 "tags": [
  "infrastructure, monitoring, production"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
    }
   },
   { "name": "search", "label": "String Match" },
   {
    "name": "app",
    "label": "App",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "bargauge",
     "description": "Resource pressure via PSI",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU"
      },
      {
       "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Mem"
      },
      {
       "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "I/O"
      },
      {
       "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Irq"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100, 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sys Load",
     "type": "gauge",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Real RAM usage excluding cache and reclaimable memory",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100, 0)"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Overall CPU busy percentage (averaged across all cores)",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Per-interface network traffic (receive and transmit) in bits per second",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Tx {{device}} "
      }
     ]
    },
    {
     "title": "Disk Read/Write IOps",
     "type": "timeseries",
     "description": "Number of I/O operations completed per second for the device (after merges), including both reads and writes",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Container Memory",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 7, "x": 17, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes / 1024/1024/1024",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Container CPU Usage %",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total[5m]) * 100",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Container Restarts (last hour)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "changes(container_start_time_seconds[1h])",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RabbitMQ Resources %",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(rabbitmq_node_mem_used / rabbitmq_node_mem_limit) * 100",
       "legendFormat": "Memory"
      },
      {
       "expr": "(rabbitmq_node_fd_used / rabbitmq_node_fd_total) * 100",
       "legendFormat": "File Descriptors"
      }
     ]
    },
    {
     "title": "RabbitMQ Consumers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_queue_consumers)" }
     ]
    },
    {
     "title": "RabbitMQ Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_connections)" }
     ]
    },
    {
     "title": "RabbitMQ Channels",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_channels)" }
     ]
    },
    {
     "title": "RabbitMQ Nodes Running",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_running)" }
     ]
    },
    {
     "title": "RabbitMQ Exchanges",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_exchanges)" }
     ]
    },
    {
     "title": "RabbitMQ Publish Rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_messages_publish_rate)"
      }
     ]
    },
    {
     "title": "RabbitMQ Messages",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(rabbitmq_queue_messages)" }
     ]
    },
    {
     "title": "RabbitMQ Messages Ready",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready)"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 254 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"$app\"} |= \"$search\" | logfmt"
      }
     ]
    }
   ]
  }
 ]
}